### ISSUE TITLE
Numerical gradient estimation

### ISSUE THREAD

**Issue by akuz** [yixuan/LBFGSpp#1]
Hi Yixuan. Do you think it would be possible to make a version where the gradient could be estimated numerically? I am trying to optimise the parameters of the covariance functions (kernels) in a Gaussian Process, and I am not sure if I can compute the gradient explicitly there. (Alternatively, if you have any pointers on how to estimate the derivative of the log-likelihood of the GP w.r.t. parameters of the kernels, I would really appreciate it.) Thanks!

**Comment by akuz** [comment]
Oh sorry, I immediately found that I can compute the gradient w.r.t. GP parameters explicitly here: http://www.gaussianprocess.org/gpml/chapters/RW5.pdf - thanks so much for your very useful contributions (this project and Spectra)!

**Comment by yixuan** [comment]
That's great. And you can also try some derivative-free optimization solvers like the Nelder-Mead algorithm.
