### ISSUE TITLE
Allow to use symbolic Hessian

### ISSUE THREAD

**Issue by cryoff** [yixuan/LBFGSpp#11]
Hello! It is an awesome library, thank you!

I have one question - do you plan to support an option to use a symbolic (so, not numerically approximated) Hessian? I have some small-scale problem which requires high accuracy and therefore the symbolic Hessian suits better than numerical one.

**Comment by yixuan** [comment]
L-BFGS is a **quasi**-Newton method, meaning that it does not require an exact Hessian matrix. If you have access to the Hessian matrix, then you can directly apply the Newton's method.
