### ISSUE TITLE
Use LBFGS++ with Spectra

### ISSUE THREAD

**Issue by drelatgithub** [yixuan/LBFGSpp#13]
Thank you for making these two amazing libraries! Currently, I would like to the two libraries in my project. However, if I use both LBFGS++ and Spectra in a single translation unit, I would encounter compiling errors saying that symbol `BKLDLT` is undefined. A minimum code example to reproduce the problem is
```C++
#include "Spectra/MatOp/DenseSymShiftSolve.h"
#include "LBFGSpp/LBFGS.h"
```

I guess that the problem I encountered is due to the same include guard name `BK_LDLT_H` in the files named `BKLDLT.h` presented in both libraries as header dependencies. The library included later would see its `BKLDLT.h` as an almost empty file because the library included earlier already defines `BK_LDLT_H`. Normally that would be okay, because the contents in one file are simply reused for both libraries, but in this case the 2 `BKLDLT.h` files are almost identical except that they define class template `BKLDLT` in *different namespaces*, which makes the file in one library unusable for the other.

The problem goes away if I rename the include guard macros to make them different (such as `LBFGSPP_BK_LDLT_H` and `SPECTRA_BK_LDLT_H`). IMO this makes the header only libraries more separated and makes the include guard collisions highly unlikely. I'm curious to know what you think!

**Comment by yixuan** [comment]
Hi @drelatgithub, thanks for pointing this out. You are right, and that's why I have added extra prefix in this commit: https://github.com/yixuan/spectra/commit/ce79ea5f12226c5e047000a63d4d294d0d653a95.

This commit belongs to a development branch (https://github.com/yixuan/spectra/tree/1.y.z), so it is not in the master branch yet.

**Comment by drelatgithub** [comment]
Thanks for the reply! I didn't know that the changes were already there! Guess I'll sit back and look forward to the new release!
