### ISSUE TITLE
the include file cause problems

### ISSUE THREAD

**Issue by cheungbs** [yixuan/LBFGSpp#16]
in the file "LBFGSpp/include/LBFGSpp/LineSearchMoreThuente.h"
the line 9: 
     #include "LBFGSpp/Param.h" make compilation fail

when modify it to be "#include "Param.h" compilation is sucessful

**Comment by JonasZehn** [comment]
There is a good chance that this can be resolved if you add absolutePath("LBFGSpp/include") to the include directories of your compiler / development environment and it's not a problem with the library.

**Comment by cheungbs** [comment]
> There is a good chance that this can be resolved if you add absolutePath("LBFGSpp/include") to the include directories of your compiler / development environment and it's not a problem with the library.

yes, you are right. but this may make things more complex.
