### ISSUE TITLE
Github Release?

### ISSUE THREAD

**Issue by nileshpatra** [yixuan/LBFGSpp#19]
Hi,

Could you please tag in a new release?

Also on a related note: Will it somehow be possible to merge your work into https://github.com/chokkan/liblbfgs (i.e. the upstream)?

**Comment by nileshpatra** [comment]
CC: @yixuan

**Comment by yixuan** [comment]
Hi @nileshpatra, my own point of view is that LBFGS++ is a relatively simple program, and I tend to keep it simple. The master branch simply reflects the latest version.

LBFGS++ is somewhat a rewrite of liblbfgs into header-only C++. Originally I just used it for my own projects, so I just keep it as a separate (hobby) project.

**Comment by nileshpatra** [comment]
Hi @yixuan 

> Hi @nileshpatra, my own point of view is that LBFGS++ is a relatively simple program, and I tend to keep it simple. The master branch simply reflects the latest version.

> LBFGS++ is somewhat a rewrite of liblbfgs into header-only C++. Originally I just used it for my own projects, so I just keep it as a separate (hobby) project.

As you might've noticed, bustools actually uses your great work and builds their code base on the library. Now, bustools is a Debian package, and we (team-wise) maintain it.
Since your package is also a dependency, I packaged it and uploaded, so users could simply `sudo apt install lib
lbfgspp-dev` (when this gets accepted) and use your nice work

The problem with unreleased repositories is that it is very hard to track any API changes, and nearly impossible to fix things if stuff goes south. Versioned releases for libraries is always encouraged and particularly important to us (as downstream). Hence, please consider tagging a release.

I understand that this might be a hobby project for you -- there are several such hobby projects that are very useful, and releasing them with proper versions is always very helpful thing for us. Please consider tagging a release if you are convinced. If you need more explanation, let me know

**Comment by yixuan** [comment]
OK, I'll do it later. Thanks!

**Comment by nileshpatra** [comment]
@yixuan gentle ping?

**Comment by yixuan** [comment]
Sorry for the delay. I just created a release, and I plan to add some automated tests in the next version.
