### ISSUE TITLE
LineSearchNocedalWright - NaN in Step 2 (Zooming)

### ISSUE THREAD

**Issue by MatthiasJeuthe** [yixuan/LBFGSpp#27]
In LineSearchNocedalWright.h (line 145, 146):
            step = (fx_hi - fx_lo) * step_lo - (step_hi * step_hi - step_lo * step_lo) * dg_lo / 2;
            step /= (fx_hi - fx_lo) - (step_hi - step_lo) * dg_lo;

Step is not checked against division by zero.

**Comment by yixuan** [comment]
This has been fixed in https://github.com/yixuan/LBFGSpp/commit/76ac83f1f885e2e7052d64eae3c49b3881b5a5b7.
