### ISSUE TITLE
How to create a functor for LBFGSpp given objective function and its gradient

### ISSUE THREAD

**Issue by FahadRazaKhan** [yixuan/LBFGSpp#28]
Hi Prof. Yi Xuan,

Thank you for sharing this library. I don't know much about optimization and C++ functors. I am trying to convert an optimization problem from Python SciPy Optimize to C++ using your library. However, in Python, the input arguments to the minimize method are scalar objective function and its gradient among others.  I have the analytic solution of the gradient and I have implemented it as a function that returns an Eigen vector. But I am struggling to convert these into a functor so that I can give it to LBFGSpp.

**Comment by yixuan** [comment]
You need some basic C++ knowledge, of course. Feel free to reopen this issue if you need more help.
