### ISSUE TITLE
compare with some  optimization tools?

### ISSUE THREAD

**Issue by longjianquan** [yixuan/LBFGSpp#29]
some simple function
 problem           other tools              calculate time       tol
problem1              osqp                                ?                          ?
problem2               ipopt                              ?
probleme              acado                            ?
would you like to share this compare data?
thanks

**Comment by yixuan** [comment]
If you want to test LBFGS++ on some larger problems, probably you can look at the [CUTEst](https://github.com/ralna/CUTEst) test suite.

**Comment by yixuan** [comment]
[This project](https://github.com/yixuan/cutest-lbfgs) may be what you need.
