### ISSUE TITLE
Division by zero in BFGSMat.h (apply_Hv(...))

### ISSUE THREAD

**Issue by ArmandLfd** [yixuan/LBFGSpp#31]
Hello, first of all, thanks for this amazing library. 

As in issue #18,  I found out that division by zero could sometimes happen while working with the library. In my case, it happened during the call of `apply_Hv(...)` in `BFGSMat.h` due to zero scalar values (`m_ys` and/or `m_theta` ) set in `add_correction` of the same file. I have to admit that I do not know if it is "mathematically/theoretically" possible to have `m_ys` and/or `m_theta` set to zero. It happened when I redid the procedure of the article `DOI: 10.1109/TVCG.2018.2810279`.

Anyway, I fixed it, on my side, as you did in issue #18:
```
const Scalar eps = std::numeric_limits<Scalar>::epsilon();
m_ys[loc] = ys;
if (m_ys[loc] < eps) m_ys[loc] = eps;

m_theta = m_y.col(loc).squaredNorm() / m_ys[loc];
if (m_theta < eps) m_theta = eps;
```

**Comment by yixuan** [comment]
Assuming you were using `LBFGSSolver` (the unconstrained solver), I tried to solve this issue using a different method (https://github.com/yixuan/LBFGSpp/commit/0fe0cb2b67e0025f20d3076ce95c1c8d3dde1240). Could you help test if the current commit solves your problem? Thanks.

**Comment by yixuan** [comment]
Let me close this first, and feel free to reopen if further issues occur.
