### ISSUE TITLE
`dg_hi` set but never used warning in LBFGSpp/LineSearchNocedalWright.h ?

### ISSUE THREAD

**Issue by WhateverLiu** [yixuan/LBFGSpp#35]
By inspecting the code it seems indeed `dg_hi ` only appears on the left side of the assignments in `LineSearchNocedalWright.h`?

**Comment by yixuan** [comment]
Good catch. It has been fixed in https://github.com/yixuan/LBFGSpp/commit/0a32ccb3259851af2faa42d4f3eba85a3f8304b8. Thanks!
